FROM python:3.12.1-alpine3.19

RUN apk update
RUN apk upgrade
RUN apk add git

COPY . /app

WORKDIR app

RUN pip3 install --upgrade pip
RUN pip3 install --upgrade setuptools wheel


ARG API_TOKEN
ENV API_TOKEN=${API_TOKEN}
ARG ENVIRONMENT
ENV ENVIRONMENT=${ENVIRONMENT}


ENV AWS_SECRET_KEY AWS_SECRET_KEY
ENV AWS_CLIENT_ID AWS_CLIENT_ID
ENV AWS_REGION_NAME AWS_REGION_NAME
ENV REDIS_HOST REDIS_HOST
ENV REDIS_PORT REDIS_PORT
ENV REDIS_PASSWORD REDIS_PASSWORD

RUN pip install -r requirements.txt

EXPOSE 8000

ENV PYTHONPATH="/app:${PYTHONPATH}"